# this makefile also gets parsed by shell scripts
# therefore it does not support full make syntax and features
# edit with care

PACKAGE          = SusyNtuple
PACKAGE_PRELOAD  = Tree
PACKAGE_CXXFLAGS = 
PACKAGE_LDFLAGS  = $(shell root-config --libs)
PACKAGE_BINFLAGS = -lCintex -lReflex -lPyROOT -lXMLParser -lEG 
PACKAGE_DEP      = SUSYTools ReweightUtils CalibrationDataInterface DGTriggerReweight JVFUncertaintyTool
PACKAGE_NOOPT    = 0

include $(ROOTCOREDIR)/Makefile-common
