# this makefile also gets parsed by shell scripts
# therefore it does not support full make syntax and features
# edit with care

PACKAGE          = SusyNtuple
PACKAGE_PRELOAD  = Graf Gpad Hist Physics Tree
PACKAGE_CXXFLAGS = 
PACKAGE_LDFLAGS  = $(shell root-config --libs --glibs)
PACKAGE_BINFLAGS = -lPyROOT -lXMLParser -lEG
PACKAGE_DEP	  	 = SUSYTools Mt2
PACKAGE_NOOPT    = 0

include $(ROOTCOREDIR)/Makefile-common
